packages:
  - apps/*
  - packages/*

catalog:
  "@orpc/client": 1.15.4
  "@orpc/openapi": 1.15.4
  "@orpc/server": 1.15.4
  "@orpc/tanstack-query": 1.15.4
  "@orpc/zod": 1.15.4
  better-auth: 1.7.7
  dotenv: ^18.0.5
  drizzle-orm: ^0.45.3
  postgres: latest
  zod: ^4.6.5

onlyBuiltDependencies:
  - cpu-features
  - esbuild
  - msgpackr-extract
  - protobufjs
  - sharp
  - ssh2

overrides:
  esbuild: ^0.28.0
  postcss: ^8.5.14
  vite: ^8.3.2
