packages:
  - apps/*
  - packages/*

catalog:
  '@orpc/client': ^1.10.0
  '@orpc/openapi': ^1.10.0
  '@orpc/server': ^1.10.0
  '@orpc/zod': ^1.10.0
  better-auth: ^1.4.5
  dotenv: ^17.2.2
  zod: 4.1.13

onlyBuiltDependencies:
  - esbuild
  - msgpackr-extract
  - sharp
