"use client";

import {
	AD,
	AE,
	AF,
	AG,
	AI,
	AL,
	AM,
	AO,
	AQ,
	AR,
	AS,
	AT,
	AU,
	AW,
	AX,
	AZ,
	BA,
	BB,
	BD,
	BE,
	BF,
	BG,
	BH,
	BI,
	BJ,
	BL,
	BM,
	BN,
	BO,
	BQ,
	BR,
	BS,
	BT,
	BW,
	BY,
	BZ,
	CA,
	CC,
	CD,
	CF,
	CG,
	CH,
	CI,
	CK,
	CL,
	CM,
	CN,
	CO,
	CR,
	CU,
	CV,
	CW,
	CX,
	CY,
	CZ,
	DE,
	DJ,
	DK,
	DM,
	DO,
	DZ,
	EC,
	EE,
	EG,
	EH,
	ER,
	ES,
	ET,
	EU,
	FI,
	FJ,
	FK,
	type FlagComponent,
	FM,
	FO,
	FR,
	GA,
	GB,
	GD,
	GE,
	GF,
	GG,
	GH,
	GI,
	GL,
	GM,
	GN,
	GP,
	GQ,
	GR,
	GS,
	GT,
	GU,
	GW,
	GY,
	HK,
	HN,
	HR,
	HT,
	HU,
	ID,
	IE,
	IL,
	IM,
	IN,
	IQ,
	IR,
	IS,
	IT,
	JE,
	JM,
	JO,
	JP,
	KE,
	KG,
	KH,
	KI,
	KM,
	KN,
	KP,
	KR,
	KW,
	KY,
	KZ,
	LA,
	LB,
	LC,
	LI,
	LK,
	LR,
	LS,
	LT,
	LU,
	LV,
	LY,
	MA,
	MC,
	MD,
	ME,
	MF,
	MG,
	MH,
	MK,
	ML,
	MM,
	MN,
	MO,
	MP,
	MQ,
	MR,
	MS,
	MT,
	MU,
	MV,
	MW,
	MX,
	MY,
	MZ,
	NA,
	NC,
	NE,
	NF,
	NG,
	NI,
	NL,
	NO,
	NP,
	NR,
	NU,
	NZ,
	OM,
	PA,
	PE,
	PF,
	PG,
	PH,
	PK,
	PL,
	PM,
	PN,
	PR,
	PS,
	PT,
	PW,
	PY,
	QA,
	RE,
	RO,
	RS,
	RU,
	RW,
	SA,
	SB,
	SC,
	SD,
	SE,
	SG,
	SI,
	SJ,
	SK,
	SL,
	SM,
	SN,
	SO,
	SR,
	SS,
	ST,
	SV,
	SX,
	SY,
	SZ,
	TC,
	TD,
	TG,
	TH,
	TJ,
	TK,
	TL,
	TM,
	TN,
	TO,
	TR,
	TT,
	TV,
	TW,
	TZ,
	UA,
	UG,
	US,
	UY,
	UZ,
	VA,
	VC,
	VE,
	VG,
	VI,
	VN,
	VU,
	WF,
	WS,
	XK,
	YE,
	YT,
	ZA,
	ZM,
	ZW,
} from "country-flag-icons/react/3x2";
import { Globe } from "lucide-react";

export interface RegionInfo {
	value: string;
	label: string;
	Flag: FlagComponent | typeof Globe;
	continent?: string;
}

export interface ContinentGroup {
	continent: string;
	regions: RegionInfo[];
}

// All countries organized by continent
export const REGIONS_BY_CONTINENT: ContinentGroup[] = [
	{
		continent: "Africa",
		regions: [
			{ value: "dz", label: "Algeria", Flag: DZ, continent: "Africa" },
			{ value: "ao", label: "Angola", Flag: AO, continent: "Africa" },
			{ value: "bj", label: "Benin", Flag: BJ, continent: "Africa" },
			{ value: "bw", label: "Botswana", Flag: BW, continent: "Africa" },
			{ value: "bf", label: "Burkina Faso", Flag: BF, continent: "Africa" },
			{ value: "bi", label: "Burundi", Flag: BI, continent: "Africa" },
			{ value: "cm", label: "Cameroon", Flag: CM, continent: "Africa" },
			{ value: "cv", label: "Cape Verde", Flag: CV, continent: "Africa" },
			{
				value: "cf",
				label: "Central African Republic",
				Flag: CF,
				continent: "Africa",
			},
			{ value: "td", label: "Chad", Flag: TD, continent: "Africa" },
			{ value: "km", label: "Comoros", Flag: KM, continent: "Africa" },
			{ value: "cg", label: "Congo", Flag: CG, continent: "Africa" },
			{ value: "cd", label: "Congo (DRC)", Flag: CD, continent: "Africa" },
			{ value: "ci", label: "Côte d'Ivoire", Flag: CI, continent: "Africa" },
			{ value: "dj", label: "Djibouti", Flag: DJ, continent: "Africa" },
			{ value: "eg", label: "Egypt", Flag: EG, continent: "Africa" },
			{
				value: "gq",
				label: "Equatorial Guinea",
				Flag: GQ,
				continent: "Africa",
			},
			{ value: "er", label: "Eritrea", Flag: ER, continent: "Africa" },
			{ value: "et", label: "Ethiopia", Flag: ET, continent: "Africa" },
			{ value: "ga", label: "Gabon", Flag: GA, continent: "Africa" },
			{ value: "gm", label: "Gambia", Flag: GM, continent: "Africa" },
			{ value: "gh", label: "Ghana", Flag: GH, continent: "Africa" },
			{ value: "gn", label: "Guinea", Flag: GN, continent: "Africa" },
			{ value: "gw", label: "Guinea-Bissau", Flag: GW, continent: "Africa" },
			{ value: "ke", label: "Kenya", Flag: KE, continent: "Africa" },
			{ value: "ls", label: "Lesotho", Flag: LS, continent: "Africa" },
			{ value: "lr", label: "Liberia", Flag: LR, continent: "Africa" },
			{ value: "ly", label: "Libya", Flag: LY, continent: "Africa" },
			{ value: "mg", label: "Madagascar", Flag: MG, continent: "Africa" },
			{ value: "mw", label: "Malawi", Flag: MW, continent: "Africa" },
			{ value: "ml", label: "Mali", Flag: ML, continent: "Africa" },
			{ value: "mr", label: "Mauritania", Flag: MR, continent: "Africa" },
			{ value: "mu", label: "Mauritius", Flag: MU, continent: "Africa" },
			{ value: "yt", label: "Mayotte", Flag: YT, continent: "Africa" },
			{ value: "ma", label: "Morocco", Flag: MA, continent: "Africa" },
			{ value: "mz", label: "Mozambique", Flag: MZ, continent: "Africa" },
			{ value: "na", label: "Namibia", Flag: NA, continent: "Africa" },
			{ value: "ne", label: "Niger", Flag: NE, continent: "Africa" },
			{ value: "ng", label: "Nigeria", Flag: NG, continent: "Africa" },
			{ value: "re", label: "Réunion", Flag: RE, continent: "Africa" },
			{ value: "rw", label: "Rwanda", Flag: RW, continent: "Africa" },
			{
				value: "st",
				label: "São Tomé and Príncipe",
				Flag: ST,
				continent: "Africa",
			},
			{ value: "sn", label: "Senegal", Flag: SN, continent: "Africa" },
			{ value: "sc", label: "Seychelles", Flag: SC, continent: "Africa" },
			{ value: "sl", label: "Sierra Leone", Flag: SL, continent: "Africa" },
			{ value: "so", label: "Somalia", Flag: SO, continent: "Africa" },
			{ value: "za", label: "South Africa", Flag: ZA, continent: "Africa" },
			{ value: "ss", label: "South Sudan", Flag: SS, continent: "Africa" },
			{ value: "sd", label: "Sudan", Flag: SD, continent: "Africa" },
			{ value: "sz", label: "Eswatini", Flag: SZ, continent: "Africa" },
			{ value: "tz", label: "Tanzania", Flag: TZ, continent: "Africa" },
			{ value: "tg", label: "Togo", Flag: TG, continent: "Africa" },
			{ value: "tn", label: "Tunisia", Flag: TN, continent: "Africa" },
			{ value: "ug", label: "Uganda", Flag: UG, continent: "Africa" },
			{ value: "eh", label: "Western Sahara", Flag: EH, continent: "Africa" },
			{ value: "zm", label: "Zambia", Flag: ZM, continent: "Africa" },
			{ value: "zw", label: "Zimbabwe", Flag: ZW, continent: "Africa" },
		],
	},
	{
		continent: "Asia",
		regions: [
			{ value: "af", label: "Afghanistan", Flag: AF, continent: "Asia" },
			{ value: "am", label: "Armenia", Flag: AM, continent: "Asia" },
			{ value: "az", label: "Azerbaijan", Flag: AZ, continent: "Asia" },
			{ value: "bh", label: "Bahrain", Flag: BH, continent: "Asia" },
			{ value: "bd", label: "Bangladesh", Flag: BD, continent: "Asia" },
			{ value: "bt", label: "Bhutan", Flag: BT, continent: "Asia" },
			{ value: "bn", label: "Brunei", Flag: BN, continent: "Asia" },
			{ value: "kh", label: "Cambodia", Flag: KH, continent: "Asia" },
			{ value: "cn", label: "China", Flag: CN, continent: "Asia" },
			{ value: "cx", label: "Christmas Island", Flag: CX, continent: "Asia" },
			{ value: "cc", label: "Cocos Islands", Flag: CC, continent: "Asia" },
			{ value: "ge", label: "Georgia", Flag: GE, continent: "Asia" },
			{ value: "hk", label: "Hong Kong", Flag: HK, continent: "Asia" },
			{ value: "in", label: "India", Flag: IN, continent: "Asia" },
			{ value: "id", label: "Indonesia", Flag: ID, continent: "Asia" },
			{ value: "ir", label: "Iran", Flag: IR, continent: "Asia" },
			{ value: "iq", label: "Iraq", Flag: IQ, continent: "Asia" },
			{ value: "il", label: "Israel", Flag: IL, continent: "Asia" },
			{ value: "jp", label: "Japan", Flag: JP, continent: "Asia" },
			{ value: "jo", label: "Jordan", Flag: JO, continent: "Asia" },
			{ value: "kz", label: "Kazakhstan", Flag: KZ, continent: "Asia" },
			{ value: "kw", label: "Kuwait", Flag: KW, continent: "Asia" },
			{ value: "kg", label: "Kyrgyzstan", Flag: KG, continent: "Asia" },
			{ value: "la", label: "Laos", Flag: LA, continent: "Asia" },
			{ value: "lb", label: "Lebanon", Flag: LB, continent: "Asia" },
			{ value: "mo", label: "Macao", Flag: MO, continent: "Asia" },
			{ value: "my", label: "Malaysia", Flag: MY, continent: "Asia" },
			{ value: "mv", label: "Maldives", Flag: MV, continent: "Asia" },
			{ value: "mn", label: "Mongolia", Flag: MN, continent: "Asia" },
			{ value: "mm", label: "Myanmar", Flag: MM, continent: "Asia" },
			{ value: "np", label: "Nepal", Flag: NP, continent: "Asia" },
			{ value: "kp", label: "North Korea", Flag: KP, continent: "Asia" },
			{ value: "om", label: "Oman", Flag: OM, continent: "Asia" },
			{ value: "pk", label: "Pakistan", Flag: PK, continent: "Asia" },
			{ value: "ps", label: "Palestine", Flag: PS, continent: "Asia" },
			{ value: "ph", label: "Philippines", Flag: PH, continent: "Asia" },
			{ value: "qa", label: "Qatar", Flag: QA, continent: "Asia" },
			{ value: "sa", label: "Saudi Arabia", Flag: SA, continent: "Asia" },
			{ value: "sg", label: "Singapore", Flag: SG, continent: "Asia" },
			{ value: "kr", label: "South Korea", Flag: KR, continent: "Asia" },
			{ value: "lk", label: "Sri Lanka", Flag: LK, continent: "Asia" },
			{ value: "sy", label: "Syria", Flag: SY, continent: "Asia" },
			{ value: "tw", label: "Taiwan", Flag: TW, continent: "Asia" },
			{ value: "tj", label: "Tajikistan", Flag: TJ, continent: "Asia" },
			{ value: "th", label: "Thailand", Flag: TH, continent: "Asia" },
			{ value: "tl", label: "Timor-Leste", Flag: TL, continent: "Asia" },
			{ value: "tr", label: "Turkey", Flag: TR, continent: "Asia" },
			{ value: "tm", label: "Turkmenistan", Flag: TM, continent: "Asia" },
			{
				value: "ae",
				label: "United Arab Emirates",
				Flag: AE,
				continent: "Asia",
			},
			{ value: "uz", label: "Uzbekistan", Flag: UZ, continent: "Asia" },
			{ value: "vn", label: "Vietnam", Flag: VN, continent: "Asia" },
			{ value: "ye", label: "Yemen", Flag: YE, continent: "Asia" },
		],
	},
	{
		continent: "Europe",
		regions: [
			{ value: "ax", label: "Åland Islands", Flag: AX, continent: "Europe" },
			{ value: "al", label: "Albania", Flag: AL, continent: "Europe" },
			{ value: "ad", label: "Andorra", Flag: AD, continent: "Europe" },
			{ value: "at", label: "Austria", Flag: AT, continent: "Europe" },
			{ value: "by", label: "Belarus", Flag: BY, continent: "Europe" },
			{ value: "be", label: "Belgium", Flag: BE, continent: "Europe" },
			{
				value: "ba",
				label: "Bosnia and Herzegovina",
				Flag: BA,
				continent: "Europe",
			},
			{ value: "bg", label: "Bulgaria", Flag: BG, continent: "Europe" },
			{ value: "hr", label: "Croatia", Flag: HR, continent: "Europe" },
			{ value: "cy", label: "Cyprus", Flag: CY, continent: "Europe" },
			{ value: "cz", label: "Czech Republic", Flag: CZ, continent: "Europe" },
			{ value: "dk", label: "Denmark", Flag: DK, continent: "Europe" },
			{ value: "ee", label: "Estonia", Flag: EE, continent: "Europe" },
			{ value: "fo", label: "Faroe Islands", Flag: FO, continent: "Europe" },
			{ value: "fi", label: "Finland", Flag: FI, continent: "Europe" },
			{ value: "fr", label: "France", Flag: FR, continent: "Europe" },
			{ value: "de", label: "Germany", Flag: DE, continent: "Europe" },
			{ value: "gi", label: "Gibraltar", Flag: GI, continent: "Europe" },
			{ value: "gr", label: "Greece", Flag: GR, continent: "Europe" },
			{ value: "gg", label: "Guernsey", Flag: GG, continent: "Europe" },
			{ value: "hu", label: "Hungary", Flag: HU, continent: "Europe" },
			{ value: "is", label: "Iceland", Flag: IS, continent: "Europe" },
			{ value: "ie", label: "Ireland", Flag: IE, continent: "Europe" },
			{ value: "im", label: "Isle of Man", Flag: IM, continent: "Europe" },
			{ value: "it", label: "Italy", Flag: IT, continent: "Europe" },
			{ value: "je", label: "Jersey", Flag: JE, continent: "Europe" },
			{ value: "xk", label: "Kosovo", Flag: XK, continent: "Europe" },
			{ value: "lv", label: "Latvia", Flag: LV, continent: "Europe" },
			{ value: "li", label: "Liechtenstein", Flag: LI, continent: "Europe" },
			{ value: "lt", label: "Lithuania", Flag: LT, continent: "Europe" },
			{ value: "lu", label: "Luxembourg", Flag: LU, continent: "Europe" },
			{ value: "mk", label: "North Macedonia", Flag: MK, continent: "Europe" },
			{ value: "mt", label: "Malta", Flag: MT, continent: "Europe" },
			{ value: "md", label: "Moldova", Flag: MD, continent: "Europe" },
			{ value: "mc", label: "Monaco", Flag: MC, continent: "Europe" },
			{ value: "me", label: "Montenegro", Flag: ME, continent: "Europe" },
			{ value: "nl", label: "Netherlands", Flag: NL, continent: "Europe" },
			{ value: "no", label: "Norway", Flag: NO, continent: "Europe" },
			{ value: "pl", label: "Poland", Flag: PL, continent: "Europe" },
			{ value: "pt", label: "Portugal", Flag: PT, continent: "Europe" },
			{ value: "ro", label: "Romania", Flag: RO, continent: "Europe" },
			{ value: "ru", label: "Russia", Flag: RU, continent: "Europe" },
			{ value: "sm", label: "San Marino", Flag: SM, continent: "Europe" },
			{ value: "rs", label: "Serbia", Flag: RS, continent: "Europe" },
			{ value: "sk", label: "Slovakia", Flag: SK, continent: "Europe" },
			{ value: "si", label: "Slovenia", Flag: SI, continent: "Europe" },
			{ value: "es", label: "Spain", Flag: ES, continent: "Europe" },
			{
				value: "sj",
				label: "Svalbard and Jan Mayen",
				Flag: SJ,
				continent: "Europe",
			},
			{ value: "se", label: "Sweden", Flag: SE, continent: "Europe" },
			{ value: "ch", label: "Switzerland", Flag: CH, continent: "Europe" },
			{ value: "ua", label: "Ukraine", Flag: UA, continent: "Europe" },
			{ value: "gb", label: "United Kingdom", Flag: GB, continent: "Europe" },
			{ value: "va", label: "Vatican City", Flag: VA, continent: "Europe" },
		],
	},
	{
		continent: "North America",
		regions: [
			{ value: "ai", label: "Anguilla", Flag: AI, continent: "North America" },
			{
				value: "ag",
				label: "Antigua and Barbuda",
				Flag: AG,
				continent: "North America",
			},
			{ value: "aw", label: "Aruba", Flag: AW, continent: "North America" },
			{ value: "bs", label: "Bahamas", Flag: BS, continent: "North America" },
			{ value: "bb", label: "Barbados", Flag: BB, continent: "North America" },
			{ value: "bz", label: "Belize", Flag: BZ, continent: "North America" },
			{ value: "bm", label: "Bermuda", Flag: BM, continent: "North America" },
			{ value: "bq", label: "Bonaire", Flag: BQ, continent: "North America" },
			{
				value: "vg",
				label: "British Virgin Islands",
				Flag: VG,
				continent: "North America",
			},
			{ value: "ca", label: "Canada", Flag: CA, continent: "North America" },
			{
				value: "ky",
				label: "Cayman Islands",
				Flag: KY,
				continent: "North America",
			},
			{
				value: "cr",
				label: "Costa Rica",
				Flag: CR,
				continent: "North America",
			},
			{ value: "cu", label: "Cuba", Flag: CU, continent: "North America" },
			{ value: "cw", label: "Curaçao", Flag: CW, continent: "North America" },
			{ value: "dm", label: "Dominica", Flag: DM, continent: "North America" },
			{
				value: "do",
				label: "Dominican Republic",
				Flag: DO,
				continent: "North America",
			},
			{
				value: "sv",
				label: "El Salvador",
				Flag: SV,
				continent: "North America",
			},
			{ value: "gl", label: "Greenland", Flag: GL, continent: "North America" },
			{ value: "gd", label: "Grenada", Flag: GD, continent: "North America" },
			{
				value: "gp",
				label: "Guadeloupe",
				Flag: GP,
				continent: "North America",
			},
			{ value: "gt", label: "Guatemala", Flag: GT, continent: "North America" },
			{ value: "ht", label: "Haiti", Flag: HT, continent: "North America" },
			{ value: "hn", label: "Honduras", Flag: HN, continent: "North America" },
			{ value: "jm", label: "Jamaica", Flag: JM, continent: "North America" },
			{
				value: "mq",
				label: "Martinique",
				Flag: MQ,
				continent: "North America",
			},
			{ value: "mx", label: "Mexico", Flag: MX, continent: "North America" },
			{
				value: "ms",
				label: "Montserrat",
				Flag: MS,
				continent: "North America",
			},
			{ value: "ni", label: "Nicaragua", Flag: NI, continent: "North America" },
			{ value: "pa", label: "Panama", Flag: PA, continent: "North America" },
			{
				value: "pr",
				label: "Puerto Rico",
				Flag: PR,
				continent: "North America",
			},
			{
				value: "bl",
				label: "Saint Barthélemy",
				Flag: BL,
				continent: "North America",
			},
			{
				value: "kn",
				label: "Saint Kitts and Nevis",
				Flag: KN,
				continent: "North America",
			},
			{
				value: "lc",
				label: "Saint Lucia",
				Flag: LC,
				continent: "North America",
			},
			{
				value: "mf",
				label: "Saint Martin",
				Flag: MF,
				continent: "North America",
			},
			{
				value: "pm",
				label: "Saint Pierre and Miquelon",
				Flag: PM,
				continent: "North America",
			},
			{
				value: "vc",
				label: "Saint Vincent and the Grenadines",
				Flag: VC,
				continent: "North America",
			},
			{
				value: "sx",
				label: "Sint Maarten",
				Flag: SX,
				continent: "North America",
			},
			{
				value: "tt",
				label: "Trinidad and Tobago",
				Flag: TT,
				continent: "North America",
			},
			{
				value: "tc",
				label: "Turks and Caicos Islands",
				Flag: TC,
				continent: "North America",
			},
			{
				value: "us",
				label: "United States",
				Flag: US,
				continent: "North America",
			},
			{
				value: "vi",
				label: "U.S. Virgin Islands",
				Flag: VI,
				continent: "North America",
			},
		],
	},
	{
		continent: "South America",
		regions: [
			{ value: "ar", label: "Argentina", Flag: AR, continent: "South America" },
			{ value: "bo", label: "Bolivia", Flag: BO, continent: "South America" },
			{ value: "br", label: "Brazil", Flag: BR, continent: "South America" },
			{ value: "cl", label: "Chile", Flag: CL, continent: "South America" },
			{ value: "co", label: "Colombia", Flag: CO, continent: "South America" },
			{ value: "ec", label: "Ecuador", Flag: EC, continent: "South America" },
			{
				value: "fk",
				label: "Falkland Islands",
				Flag: FK,
				continent: "South America",
			},
			{
				value: "gf",
				label: "French Guiana",
				Flag: GF,
				continent: "South America",
			},
			{ value: "gy", label: "Guyana", Flag: GY, continent: "South America" },
			{ value: "py", label: "Paraguay", Flag: PY, continent: "South America" },
			{ value: "pe", label: "Peru", Flag: PE, continent: "South America" },
			{
				value: "gs",
				label: "South Georgia",
				Flag: GS,
				continent: "South America",
			},
			{ value: "sr", label: "Suriname", Flag: SR, continent: "South America" },
			{ value: "uy", label: "Uruguay", Flag: UY, continent: "South America" },
			{ value: "ve", label: "Venezuela", Flag: VE, continent: "South America" },
		],
	},
	{
		continent: "Oceania",
		regions: [
			{ value: "as", label: "American Samoa", Flag: AS, continent: "Oceania" },
			{ value: "au", label: "Australia", Flag: AU, continent: "Oceania" },
			{ value: "ck", label: "Cook Islands", Flag: CK, continent: "Oceania" },
			{ value: "fj", label: "Fiji", Flag: FJ, continent: "Oceania" },
			{
				value: "pf",
				label: "French Polynesia",
				Flag: PF,
				continent: "Oceania",
			},
			{ value: "gu", label: "Guam", Flag: GU, continent: "Oceania" },
			{ value: "ki", label: "Kiribati", Flag: KI, continent: "Oceania" },
			{
				value: "mh",
				label: "Marshall Islands",
				Flag: MH,
				continent: "Oceania",
			},
			{ value: "fm", label: "Micronesia", Flag: FM, continent: "Oceania" },
			{ value: "nr", label: "Nauru", Flag: NR, continent: "Oceania" },
			{ value: "nc", label: "New Caledonia", Flag: NC, continent: "Oceania" },
			{ value: "nz", label: "New Zealand", Flag: NZ, continent: "Oceania" },
			{ value: "nu", label: "Niue", Flag: NU, continent: "Oceania" },
			{ value: "nf", label: "Norfolk Island", Flag: NF, continent: "Oceania" },
			{
				value: "mp",
				label: "Northern Mariana Islands",
				Flag: MP,
				continent: "Oceania",
			},
			{ value: "pw", label: "Palau", Flag: PW, continent: "Oceania" },
			{
				value: "pg",
				label: "Papua New Guinea",
				Flag: PG,
				continent: "Oceania",
			},
			{
				value: "pn",
				label: "Pitcairn Islands",
				Flag: PN,
				continent: "Oceania",
			},
			{ value: "ws", label: "Samoa", Flag: WS, continent: "Oceania" },
			{ value: "sb", label: "Solomon Islands", Flag: SB, continent: "Oceania" },
			{ value: "tk", label: "Tokelau", Flag: TK, continent: "Oceania" },
			{ value: "to", label: "Tonga", Flag: TO, continent: "Oceania" },
			{ value: "tv", label: "Tuvalu", Flag: TV, continent: "Oceania" },
			{ value: "vu", label: "Vanuatu", Flag: VU, continent: "Oceania" },
			{
				value: "wf",
				label: "Wallis and Futuna",
				Flag: WF,
				continent: "Oceania",
			},
		],
	},
];

// Flatten all regions for easy lookup
export const ALL_REGIONS: RegionInfo[] = REGIONS_BY_CONTINENT.flatMap(
	(group) => group.regions,
);

// Complete mapping of region codes to display info
export const REGION_MAPPING: Record<string, RegionInfo> = {
	// Legacy worker regions (for backwards compatibility)
	"na-canada": {
		value: "na-canada",
		label: "North America",
		Flag: CA,
	},
	"sa-brazil": {
		value: "sa-brazil",
		label: "South America",
		Flag: BR,
	},
	"eu-general": {
		value: "eu-general",
		label: "Europe",
		Flag: EU,
	},
	"ap-hongkong": {
		value: "ap-hongkong",
		label: "Asia/Pacific",
		Flag: HK,
	},
	global: {
		value: "global",
		label: "Global",
		Flag: AQ,
	},
	"oc-syd": {
		value: "oc-syd",
		label: "Oceania",
		Flag: AU,
	},
	// Add all new regions to mapping
	...Object.fromEntries(ALL_REGIONS.map((region) => [region.value, region])),
};

// List of all regions for worker creation (legacy - kept for backwards compatibility)
/* export const WORKER_REGIONS: RegionInfo[] = [
	{ value: "na-canada", label: "North America", Flag: CA },
	{ value: "sa-brazil", label: "South America", Flag: BR },
	{ value: "eu-general", label: "Europe", Flag: EU },
	{ value: "ap-hongkong", label: "Asia/Pacific", Flag: HK },
	{ value: "global", label: "Global", Flag: AQ },
];
*/

/**
 * Retrieve RegionInfo for a given region code, returning a fallback entry with the Globe flag when the code is unknown.
 *
 * @param regionCode - The region code to look up (e.g., "us", "eu-general", "global").
 * @returns The matching RegionInfo from REGION_MAPPING, or a fallback RegionInfo whose `value` and `label` equal `regionCode` and whose `Flag` is `Globe`.
 */
export function getRegionInfo(regionCode: string): RegionInfo {
	return (
		REGION_MAPPING[regionCode] || {
			value: regionCode,
			label: regionCode,
			Flag: Globe,
		}
	);
}
